### ISSUE TITLE
Investigating other K/V store options

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#133]
There're other K/V store choices options:

- https://github.com/dgraph-io/badger
- https://github.com/etcd-io/bbolt
- https://github.com/syndtr/goleveldb

We need to investigate if these are good alternative we should migrate to. Some considerations in my mind:

1. Operation cost
2. Read/write performance
3. Storage footprint

**Comment by shisoft** [comment]
Just explaining our discussion last time on the phone about your discovery. Bolt have better space efficiency than LSM-tree based badger and LevelDB is because it use B-tree, which is an in-place approach with potential write amplification and random writes. LSM-tree in the other hand, deletion does not happened when it is requested, but postponed to level merging process. That may explain why it cost more disk space as you mentioned. LSM-tree based database also have better write performance for it appends data on disk, this can benefit both SSD and spinning disk hardwares.
