### ISSUE TITLE
Failed to get state from time to time when running a node

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1540]
### What version of iotex-core are you using (`ioctl version`)?

0.8.3+

### What operating system and processor architecture are you using?

All

### What did you do? If possible, provide a recipe for reproducing the error.

Run a node and joining the mainnet

### What did you expect to see?

No error of about getting states

### What did you see instead?

```
{"level":"error","ts":1570507414.8812747,"caller":"evm/evmstatedbadapter.go:585","msg":"Failed to get state.","ioAddr":"io1ckvhh2nym5ejehklmn3ql6c52f6nfdnguspj5n","networkAddr":"0.0.0.0:4689","error":"not exist in trie","errorVerbose":"not exist in trie\ngithub.com/iotexproject/iotex-core/db/trie.init.ializers\n\t/go/apps/iotex-core/db/trie/trie.go:37\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:188\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
```

**Comment by zjshen14** [comment]
It's not affecting the node to continue run

**Comment by lzxm160** [comment]
when create evm, go-ethereum's gasSStore will call StateDBAdapter's getState,test a lot but didn't find the reason,need to find out  contract's getState and setState if have logical error

**Comment by lzxm160** [comment]
There're two cases can cause this error:
1、If global variable in contract is not initialized or set,when reading this variable will cause this error,because it's not exists in contract's storage trie
2、When we initialize or set global variable in contract for the first time,ethereum's gasSStore will call iotex-core's getState,this error will be caused

After initialize or set this global variable,this error will disappear
