### ISSUE TITLE
delegate in probation list may stuck in probation list if they drop off as delegate during their probation

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#2193]
https://github.com/iotexproject/iotex-core/blob/3946991fc2cf07e565503143cd1e55eb0abcaed4/action/protocol/poll/slasher.go#L403

```golang
	prevProbationlist, _, err := sh.getProbationList(sm, false)
	if err != nil {
		return nil, errors.Wrap(err, "failed to read latest probation list")
	}
	probationMap := prevProbationlist.ProbationInfo
	if probationMap == nil {
		probationMap = make(map[string]uint32)
	}
	skipList := upd.ReadOldestUPD()
	for _, addr := range skipList {
		if _, ok := probationMap[addr]; !ok {
			log.L().Fatal("skipping list element doesn't exist among one of existing map")
			continue
		}
		probationMap[addr]--
	}
	addList, err := sh.calculateUnproductiveDelegatesByEpoch(ctx, sm, rp, epochNum-1)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to calculate current epoch upd %d", epochNum-1)
	}
	if err := upd.AddRecentUPD(addList); err != nil {
		return nil, errors.Wrap(err, "failed to add recent upd")
	}
	for _, addr := range addList {
		if _, ok := probationMap[addr]; ok {
			probationMap[addr]++
			continue
		}
		probationMap[addr] = 1
	}

	for addr, count := range probationMap {
		if count == 0 {
			delete(probationMap, addr)
		}
	}
```

based on above code, probation counts on a probated delegate decrease when delegate can be read from `ReadOldestUPD`. `udp` is calculated by `calculateUnproductiveDelegatesByEpoch`. If a delegate is no long a valid delegate(unstake, < 1.2m selfstake), then it will never get returned from `calculateUnproductiveDelegatesByEpoch` regardless its productivity. So a probated delegate who also drop off from being a delegate, it will not included in `udp` and returned from `ReadOldestUPD`, that means the counter on it probation status will never decrease again.

**Comment by koseoyoung** [comment]
I still can't understand b/c ```ReadOldestUPD``` should return the oldest upd which calculated from ```calculateUnproductiveDelegatesByEpoch``` when he didn't unstake yet.
For example, let's assume on epoch 100, some delegate(A) is returned as an unproductive delegate, so it starts to get probated.
Then after 6 epochs, he(A) is no longer unproductive delegate (because he deregisters). In this case, the ```ReadOldestUPD``` will still return oldest upd that we calculated and stored 6 epochs ago which includes (A) delegate, so decreasing should work well. ```ReadOldestUPD``` will return the oldest upd information in stateDB, so my thought is the counter should decrease.

**Comment by yutongp** [comment]
after another round of investigation. this is an issue regrading to before easter and enter easter, probation calculation. @koseoyoung is looking into the details. this bug won't impact mainnet. just testnet

**Comment by koseoyoung** [comment]
The root cause is related to easter. Because we are including calculation of easter-1 unproductive delegate, Probationlist[easter + 6] has 7 epochs data [easter -1, easter + 6]. But the upd list only holds 6 epochs data, and delete oldest data automatically. So when we calculate probationlist[easter + 7] the oldest upd data is upd[easter], there is no upd[easter-1]. That’s why 1 count from upd[easter-1] can not be decreased.

**Comment by koseoyoung** [comment]
ideally, there are two options
1. we can calculate probationlist from easter + 1
2. we can change this line to epochNum < easterEpochNum + sh.probationEpochPeriod https://github.com/iotexproject/iotex-core/blob/master/action/protocol/poll/slasher.go#L369

This issue won't happen on mainnet

**Comment by yutongp** [comment]
close this issue. we are not going to fix it
