### ISSUE TITLE
poll/slasher read state by default read latest state date if it encountered a ErrIndexerNotExist err

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#2194]
https://github.com/iotexproject/iotex-core/blob/master/action/protocol/poll/slasher.go#L121

in above code, with all read methods, if indexer returned an `ErrIndexerNotExist`, it will by default fallback to read current epoch data.

as a result, when user try to read probation list from epoch before easter(when probation is not yet enabled), user will get probation list from current epoch:
```
./ioctl node probationlist -e 1
EpochNumber : 1, IntensityRate : 90%
ProbationList : [
  "io1gh439pm67d4cwxt882xpylj75klys6esepml60"
]
```

Please verify if this behavior is an expected feature or a possible bug.

**Comment by koseoyoung** [comment]
I think it should read from historical state reader(archive mode) here about old data https://github.com/iotexproject/iotex-core/blob/master/api/api.go#L860, and should return error (not support archive mode) in case of ErrIndexerNotExist. But currently on the client side, we are not putting height argument (https://github.com/iotexproject/iotex-proto/blob/master/proto/api/api.proto#L289) so it’s just reading from current state reader. I will change the client side to try to fix this issue.

**Comment by koseoyoung** [comment]
I fix client side to call historical state reader. 
To sum up, readstate API logic in poll protocol with given "old" epoch request 
1. look up candidate indexer (gateway enabled node)
2. look up historical state reader (archive node)

In case of before easter, since currently archive mode is not supported, it returns archive mode not supported error. However In future it should return not found error I think.
