### ISSUE TITLE
[test] simplify test code

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3065]
**What would you like to be added**:
in this commit: https://github.com/iotexproject/iotex-core/commit/892dee9bcf9c7e93efdca1b6c4ade0df21be0e4d#diff-701eab62dfc97c42c827070546fe92f9a280aa70934241aec736cf6402c6be69, `addOneTx()` is a new func to simplify the test code

use it to simplify the following as well:
1. `func addTestingConstantinopleBlocks`
2. `func TestNativeStaking`

**Why is this needed**:
squash lines of test code

**Comment by LuckyPigeon** [comment]
@dustinxie Can I take this issue?

**Comment by raullenchai** [comment]
> @dustinxie Can I take this issue?

Pls do!

**Comment by LuckyPigeon** [comment]
Besides `func addTestingConstantinopleBlocks` and `func TestNativeStaking`, there are still a few files that can be simplify by `addOneTx`. Such as `func addTestingTsfBlocks`, `func addTestingBlocks` and more.
How about add `addOneTx` as a `testutil`, so that we don't need to declare `addOneTx` at every single function and can still achieve simplify test code.
