### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3232]
### What version of iotex-core are you using (`ioctl version`)?
commit https://github.com/iotexproject/iotex-core/commit/4c8543c0c286b6db46c22be2e2b2b50d0bd4f1e3 caused docker build to fail

### What did you see instead?
here's the docker build log:
```
#26 [stage-1 10/12] RUN touch /var/lib/logrotate.status
#26 sha256:4c14e46ba47bff0e636e9257baaec63985e2100bd8263e6a74049ff582e02d98
#26 DONE 0.6s
#27 [stage-1 11/12] RUN chmod -R u=rwX,go=rX /etc
#27 sha256:f3f1e4d3c2e41172e2ba9b7ae3bcd8c0ef7d798980034a53031b0e1b5cc7b571
#27 0.639 chmod: /etc/hosts: Read-only file system
#27 0.776 chmod: /etc/resolv.conf: Read-only file system
#27 ERROR: executor failed running [/bin/sh -c chmod -R u=rwX,go=rX /etc]: exit code: 1
------
> [stage-1 11/12] RUN chmod -R u=rwX,go=rX /etc:
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c chmod -R u=rwX,go=rX /etc]: exit code: 1
Build failed using Buildkit
```

**Comment by jrynkiew** [comment]
What version of Docker are you running, what operating system, and what OS architecture? Do you run it as a privileged user? I think it's a Buildkit issue, not directly related to Docker. I will check. How did you enable Buildkit? In the config files?

**Comment by jrynkiew** [comment]
I read more into it - there is a Docker BuildKit support thread here - https://github.com/moby/buildkit/issues/1267

It appears that the issue is related to the base image we use for Docker. The root folders are not writeable.

I think the real problem is not `RUN chmod -R u=rwX,go=rX /etc`, since without it the build process _without_ BuildKit will give this error: 

```
Potentially dangerous mode on /etc/logrotate.d/iotex: 0664
error: Ignoring /etc/logrotate.d/iotex because it is writable by group or others.
```

The problem is that the error suggests that the whole section in the Dockerfile 

```
# logrotate log file daily
RUN apk add logrotate
COPY logrotate.conf /etc/logrotate.d/iotex
RUN mkdir -p /var/lib/
RUN touch /var/lib/logrotate.status
RUN logrotate /etc/logrotate.d/iotex
```

becomes useless unless you specify `RUN chmod -R u=rwX,go=rX /etc` if you decide to use 
```
docker:
	$(DOCKERCMD) build -t $(USER)/iotex-core:latest .
```
in your Makefile.

The real fix is to force BuildKit on the Makefile 
```
docker:
	DOCKER_BUILDKIT=1 $(DOCKERCMD) build -t $(USER)/iotex-core:latest .
``` 
and then remove the 
```
RUN chmod -R u=rwX,go=rX /etc
``` 
command from the Dockerfile

**Comment by Liuhaai** [comment]
[The explaination in the post](https://github.com/moby/buildkit/issues/1267#issuecomment-768903038) seems reasonable.
