### ISSUE TITLE
[ioctl] Replace `NewMockServiceClient` with `NewMockCoreService` and remove `ServiceClient`

### ISSUE THREAD

**Issue by Liuhaai** [iotexproject/iotex-core#3256]
**What would you like to be added**:

**Why is this needed**:
Both interfaces are similar

**Comment by huof6829** [comment]
hi,  i think this maybe fail.  Because NewMockServiceClient  is used for ioctl to send message to grpc server.   but NewMockCoreService is the interface of grpc server.   The functions of them is different.  for example :   `GetAccount ` https://github.com/iotexproject/iotex-core/blob/b08b16162f12e486c4eaa8c9266d759273019097/ioctl/newcmd/account/accountbalance_test.go#L46

**Comment by Liuhaai** [comment]
> @Liuhaai hi, i think this maybe fail. Because NewMockServiceClient is used for ioctl to send message to grpc server. but NewMockCoreService is the interface of grpc server. The functions of them is different. for example : `GetAccount `
> 
> https://github.com/iotexproject/iotex-core/blob/b08b16162f12e486c4eaa8c9266d759273019097/ioctl/newcmd/account/accountbalance_test.go#L46

Could you check whether `./iotexapi/mock_iotexapi/mock_iotexapi.go` is usable for tests

**Comment by huof6829** [comment]
> iotexproject/iotex-proto#128

after done, i will modify iotex-core
