### ISSUE TITLE
upgrade to EVM Altair

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#3475]

**Comment by raullenchai** [comment]
Fullsync test stuck on testnet

**Comment by dustinxie** [comment]
here's the tx that cannot pass fullsync: https://testnet.iotexscout.io/tx/40fe566ea234d7db531aca486196ade1f7eb81c0b185b80c7dd238f1401bb95d

1. the culprit is identified to be: https://github.com/ethereum/go-ethereum/commit/9393d1fb5d178667e4d2750f7f540a3db5985818
2. after this commit, the consumed gas changed from `2907839` to `2892839`
3. continue investigate why it caused the gas to change

**Comment by dustinxie** [comment]
how to repro
1. good code: iotex-core/fuzzer branch
2. bad code: iotex-core/arrow branch (== fuzzer branch + culprit commit mentioned above)
3. data file: https://console.cloud.google.com/storage/browser/blockchain-golden/arrow

start fullnode using testnet config, it will run the bad block, bail out before commit, and print out the debug info

**Comment by dustinxie** [comment]
[good.log](https://github.com/iotexproject/iotex-core/files/9456144/good.log)
[bad.log](https://github.com/iotexproject/iotex-core/files/9456148/bad.log)
