### ISSUE TITLE
ioctl bc bucketlist error

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3654]
### What version of iotex-core image (or code branch) are you using?
latest

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
ioctl bc bucketlist cand binacenode --endpoint=api.iotex.one:443

### What did you expect to see?
return bucketlist voting to this candidate

### What did you see instead?
Error: grpc triggered crash: runtime error: invalid memory address or nil pointer dereference

**Comment by millken** [comment]
https://github.com/iotexproject/iotex-core/blob/7db8eafb4a4940ca021be7563ce04d39137213bd/action/protocol/staking/candidate_statereader.go#L404-L407

The bug (v1.8.2  -  v1.8.3-rc4) has been fixed in  v1.9.0-rc0
https://github.com/iotexproject/iotex-core/blob/a78461622c708f32d90ff5ac880a474978802dda/action/protocol/staking/candidate_statereader.go#L404-L407
