### ISSUE TITLE
Set Up Test Summary in Circle CI

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#602]
<img width="639" alt="screen shot 2019-02-23 at 11 56 43 am" src="https://user-images.githubusercontent.com/989846/53291053-28a90900-3762-11e9-994f-01d5b7a09c30.png">

Need to follow this
https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by raullenchai** [comment]
Done

**Comment by zjshen14** [comment]
Reopen the issue since the code was reverted: https://github.com/iotexproject/iotex-core/commit/e89987e41d3160f530777661373b7bfadd29539b

Some additional requirement:

1. We still need to keep the log so that we could debug when a test fails.
2. Investigate the problem why it became so easily to fail a bunch of tests after enabling the test summary

**Comment by raullenchai** [comment]
Close since not a must for us.
